# Generated by Django 4.2.5 on 2023-10-29 17:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dish', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='type',
            new_name='p_type',
        ),
        migrations.AlterField(
            model_name='product',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.CreateModel(
            name='Receipt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='receipt', max_length=255)),
                ('complexity', models.IntegerField(default=1)),
                ('portions', models.IntegerField(blank=True, null=True)),
                ('meal', models.CharField(blank=True, choices=[('breakfast', 'Breakfast'), ('lunch', 'Lunch'), ('dinner', 'Dinner'), ('tea', 'Tea'), ('elevenses', 'Elevenses')], max_length=10, null=True)),
                ('dish_type', models.CharField(blank=True, choices=[('salad', 'Salad'), ('soup', 'Soup'), ('pasta', 'Pasta'), ('dough', 'Dough'), ('stew', 'Stew'), ('vegetable sides', 'Vegsides'), ('sandwich', 'Sandwich'), ('sauce', 'Sauce'), ('drink', 'Drink')], max_length=20, null=True)),
                ('additional', models.ManyToManyField(blank=True, to='dish.receipt')),
            ],
        ),
        migrations.CreateModel(
            name='Instruction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(max_length=255)),
                ('time', models.FloatField(default=0.0)),
                ('is_prep', models.BooleanField(default=False)),
                ('receipt', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='instruction', to='dish.receipt')),
            ],
        ),
        migrations.CreateModel(
            name='Ingredient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.FloatField(default=0.0)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dish.product')),
                ('receipt', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='dish.receipt')),
            ],
        ),
    ]
